[build]
build = "x86_64-unknown-linux-gnu"
host = [ "@RUST_TARGET_TRIPLE@" ]
target = [ "@RUST_TARGET_TRIPLE@" ]
python = "python2.7"
full-bootstrap = false
extended = false
openssl-static = false
rustc = '@RUSTC@'
cargo = '@CARGO@'
[install]
prefix = "@TERMUX_PREFIX@"

[rust]
use-jemalloc = false
#backtrace = true
#default-linker = "clang"
#default-ar = "ar"
channel = "stable"
rpath = true
optimize-tests = false
debuginfo-tests = false
codegen-tests = false

[target.x86_64-unknown-linux-gnu]
cc = "/usr/bin/gcc"
cxx = "/usr/bin/g++"
#llvm-config = "/usr/bin/llvm-config-4.0"

[target.@RUST_TARGET_TRIPLE@]
cc = "@TERMUX_HOST_PLATFORM@-clang"
cxx = "@TERMUX_HOST_PLATFORM@-clang++"
#llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
#jemalloc = "/path/to/jemalloc/libjemalloc_pic.a"
#android-ndk = "/path/to/ndk"

